services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    hostname: frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    networks:
      - wedding-network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    hostname: backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env.production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads:rw
      - album-data:/app/public/albums:rw
    networks:
      - wedding-network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "-q", "--spider", "http://localhost:5000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wedding-network
    restart: unless-stopped
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  album-data:
    driver: local

networks:
  wedding-network:
    driver: bridge